In [50]:
import numpy as np
import pandas as pd
import math

In [51]:
def cubic_function(x):
    return pow(x, 3)

def abs_function(x):
    return np.abs(x - 0.2)

def sin_function(x):
    return x * math.sin(1/x)

In [52]:
def ExhaustiveSearch(function, a_from, b_to, epsilon=0.001):
    x_min = a_from
    y_min = function(a_from)
    iter_count = 0
    func_calls = 1
    x_step = a_from
    while x_step <= b_to:
        y_step = function(x_step)
        if y_step < y_min:
            x_min = x_step
            y_min = y_step
        x_step += epsilon
        iter_count += 1
        func_calls += 1
    return {"min": x_min, "func_min": y_min, "iterations": iter_count, "function_calls": func_calls}

In [53]:
def Dichotomy(function, a_from, b_to, epsilon=0.001):
    iterations_number = 0
    function_calls = 0
    delta = epsilon/2
    x_left = a_from
    x_right = b_to

    while (x_right - x_left) > epsilon:
        x1 = (x_left + x_right - delta) / 2
        x2 = (x_left + x_right + delta) / 2
        f_x1 = function(x1)
        f_x2 = function(x2)
        if f_x1 <= f_x2:
            x_right = x2
        else:
            x_left = x1

        iterations_number += 1
        function_calls += 2

    x_min = (x_right-x_left)/2 + x_right 
    y_min = function(x_min)
    function_calls += 1
    return {"min": x_min, "func_min": y_min, "iterations": iterations_number,"function_calls": function_calls }

In [54]:
def GoldenSection(function, a_from, b_to, epsilon=0.001):
    delta = (3 - np.sqrt(5)) / 2
    iterations_number = 0
    function_calls = 0

    x_left = a_from
    x_right = b_to

    x_x1 = x_left + (x_right - x_left) * delta
    x_x2 = x_right - (x_right - x_left) * delta
    f_x1 = function(x_x1)
    f_x2 = function(x_x2)

    while x_right - x_left > epsilon:
        if f_x1 >= f_x2:
            x_left = x_x1

            x_x1 = x_x2
            f_x1 = f_x2

            x_x2 = x_right - (x_right - x_left) * delta
            f_x2 = function(x_x2)
        else:
            x_right = x_x2

                
            x_x2 = x_x1
            f_x2 = f_x1

            x_x1 = x_left + (x_right - x_left) * delta
            f_x1 = function(x_x1)

        iterations_number += 1
        function_calls += 1

    x_min = (x_left + x_right) / 2
    y_min = round(function((x_left + x_right) / 2),4)
    function_calls += 1
    
    return {"min": x_min, "func_min": y_min, "iterations": iterations_number, "function_calls": function_calls}

In [55]:
data = []
for optimizer in ('ExhaustiveSearch', "Dichotomy", "GoldenSection"):
    for func, interval in zip(("cubic_function", "abs_function", "sin_function"), ([0, 1], [0, 1], [0.1, 1])):
        result = eval(optimizer)(eval(func), interval[0], interval[1])
        data.append(
             {"optimizer": optimizer, "func": func, "min": result["min"], "func_min": result["func_min"],\
              "iterations": result["iterations"], "function_calls": result["function_calls"]}
        )
data = pd.DataFrame(data)

In [56]:
data

,optimizer,func,min,func_min,iterations,function_calls
0,ExhaustiveSearch,cubic_function,0.000000,0.000000e+00,1000,1001
1,ExhaustiveSearch,abs_function,0.200000,1.387779e-16,1000,1001
2,ExhaustiveSearch,sin_function,0.223000,-2.172246e-01,900,901
3,Dichotomy,cubic_function,0.001482,3.255319e-09,11,23
4,Dichotomy,abs_function,0.201089,1.089233e-03,11,23
5,Dichotomy,sin_function,0.223509,-2.171930e-01,11,23
6,GoldenSection,cubic_function,0.000367,0.000000e+00,15,16
7,GoldenSection,abs_function,0.200073,1.000000e-04,15,16
8,GoldenSection,sin_function,0.222593,-2.172000e-01,15,16

In [57]:
data[data['func']=='abs_function'].loc[:,data.columns!='func']

          optimizer       min      func_min  iterations  function_calls
1  ExhaustiveSearch  0.200000  1.387779e-16        1000            1001
4         Dichotomy  0.201089  1.089233e-03          11              23
7     GoldenSection  0.200073  1.000000e-04          15              16

In [58]:
data[data['func']=='sin_function'].loc[:,data.columns!='func']

          optimizer       min  func_min  iterations  function_calls
2  ExhaustiveSearch  0.223000 -0.217225         900             901
5         Dichotomy  0.223509 -0.217193          11              23
8     GoldenSection  0.222593 -0.217200          15              16

In [59]:
data[data['func']=='cubic_function'].loc[:,data.columns!='func']

          optimizer       min      func_min  iterations  function_calls
0  ExhaustiveSearch  0.000000  0.000000e+00        1000            1001
3         Dichotomy  0.001482  3.255319e-09          11              23
6     GoldenSection  0.000367  0.000000e+00          15              16